# Generated by Django 5.1 on 2024-08-15 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_remove_comment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user_id",
        ),
    ]
